### PR TITLE
bugfix: relay gas fee estimates

### LINKED ISSUE #372: [QA] “Error: fractional component exceeds decimals” appears when user sends too small amount
#### Steps:

1. Connect Metamask wallets in ‘From’ and ‘To’ sections
2. Prepare to send ETH from Goerli to Moonbase
3. Type to small Amount, for example 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000001
4. Click “Approve and proceed with transaction” button

#### Actual results:

- “Error sending transfer, please try again” is displayed for the user
- Error is displayed in Console

```
Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at e.value (main.ebfc4165.js:2:8173830)
    at e.value (main.ebfc4165.js:2:8173974)
    at f (main.ebfc4165.js:2:8047389)
    at y (main.ebfc4165.js:2:8048379)
    at Module.c (main.ebfc4165.js:2:8334500)
    at main.ebfc4165.js:2:16947408
    at l (main.ebfc4165.js:2:15854034)
    at Generator.<anonymous> (main.ebfc4165.js:2:15855395)
    at Generator.next (main.ebfc4165.js:2:15854397)
    at n (main.ebfc4165.js:2:15847811)
```

#### Expected results:
User is informed that amount is too small

#### Note:
Issue is also reproducible when a user sends FTM from Fantom (Metamask wallet) to Solana (Phantom wallet).

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachments:

Screenshot 2023-04-19 at 13 10 28

Screenshot 2023-04-19 at 13 20 39

### LINKED ISSUE #433: [QA][Mainnet] Current estimates are not calculated
#### Environment:
https://6439cde099e912008f2bc758--wormhole-connect.netlify.app/ 

#### Steps:

1. Connect 'From' and 'To' wallets
2. Prepare to send ETH from Ethereum to BSC 
3. Type Amount, in my case “1078244.354797” (warning message shows incorrect value for minimum amount, ticket #431)
4. Observe “Gas Payment” section

#### Actual result:
Current estimates are not calculated.

#### Expected result:
Current estimates are calculated.

#### Tested device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
Screenshot 2023-04-26 at 16 54 06

### PR DESCRIPTION
**Pull request by anondev2323**
Closes #372 
Closes #433

### CODE REVIEW

File: wormhole-connect/src/sdk/gasEstimates.ts [hunk 1]
```diff
@@ -55,12 +57,15 @@ const estimateGasFee = async (
         undefined,
       );
     } else {
-      const parsedNativeAmt = toNativeToken
-        ? utils.parseUnits(toNativeToken, decimals).toString()
-        : '0';
+      const parsedNativeAmt = utils
```
Comment (M-Picco) [inline wormhole-connect/src/sdk/gasEstimates.ts]: Could these changes and those in line 108 be extracted outside the conditionals? It seems to be the same code for both Sui and Eth cases

File: wormhole-connect/src/utils/transferValidation.ts [hunk 2]
```diff
@@ -209,10 +209,16 @@ export const validateSolanaTokenAccount = (
...
+  relayerFee: number = 0,
+  toNativeToken: number = 0,
 ) => {
-  return isAutomatic ? toNativeToken + (relayerFee || 0) : 0;
+  // no minimum amount for manual transfers
+  if (!isAutomatic) return 0;
+
+  // has to be slightly higher than the minimum or else tx will revert
+  const fees = relayerFee + toNativeToken;
+  const min = (fees * 1.05).toFixed(6);
```
Comment (M-Picco) [inline wormhole-connect/src/utils/transferValidation.ts:220]: Should the decimals be 6 or 8?

Comment (anondev2323) [reply wormhole-connect/src/utils/transferValidation.ts:220]: I think 6 is enough here

**Review by M-Picco — APPROVED** [review]
