### PR TITLE
Improve Redeem view error handling & small fixes

### LINKED ISSUE #2857: Manual redeem screen says "transaction complete" when Solana transaction hasn't finished yet
image

image

### PR DESCRIPTION
**Pull request by artursapek**
## Error handling

This fixes #2857 and generally cleans things up. We now do all transfer telemetry events and UI error handling in a single `useEffect`. This means we're only relying on the `track` method now to tell us about the progress of a transaction.

The only exception to that is if `handleManualClaim` throws an error _before we've seen any other kind of final status on the receipt_ (complete, refunded, or failed).

## Icon colors

This fixes a recently introduced bug that made all of the status icons purple

## Auto-connect wallet for manual claims

Added this behavior using `useConnectToLastUsedWallet()` :)

## Call-to-action button

If a manual claim fails, we now show the redeem button again so they can try again. Before, it was showing the "Start a new transaction" button.

### CODE REVIEW

File: wormhole-connect/src/views/v2/Redeem/index.tsx [hunk 1]
```diff
@@ -164,30 +170,101 @@ const Redeem = () => {
...
   useEffect(() => {
-    // When we see the transfer was complete for the first time,
-    // fire a transfer.success telemetry event.
-    if (isTxComplete && !transferSuccessEventFired) {
-      setTransferSuccessEventFired(true);
+    const { receipt } = routeContext;
+
+    if (!receipt) return;
+
+    if (isTxComplete) {
```
Comment (kev1n-peters) [inline wormhole-connect/src/views/v2/Redeem/index.tsx:226]: We should add `isTxComplete`, `transferSuccessEventFired`, `isAutomaticRoute`, and `isTxRefunded` to this hook's deps list

Comment (kev1n-peters) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:226]: We should probably enable the linter rule for exhaustive deps in a different PR

File: wormhole-connect/src/views/v2/Redeem/index.tsx [hunk 2]
```diff
@@ -575,59 +650,51 @@ const Redeem = () => {
...
+            dispatch(setRoute('bridge'));
+          }}
+        >
+          <Typography textTransform="none">Start a new transaction</Typography>
+        </Button>
+      );
+    }
+
+    if (isTxDestQueued || !isAutomaticRoute) {
       if (isTxAttested && !isConnectedToReceivingWallet) {
```
Comment (kev1n-peters) [inline wormhole-connect/src/views/v2/Redeem/index.tsx]: When `isTxDestQueued === true`, then `isTxAttested === false` and users won't be able to connect their receiving wallet. I think we should change `isTxAttested` back to `>= TransferState.Attested` or figure out something better

File: wormhole-connect/src/utils/errors.ts [hunk 3]
```diff
@@ -41,11 +44,22 @@ export function interpretTransferError(
...
+      /burn.*exceed/i.test(e?.toString())
+    ) {
+      // As of this code being written the CCTP limit is 1,000,000 USDC in a single transfer
+      // It's possible Circle could change this in the future and we're not reading the limit
+      // from their contracts dynamically for now so we assume it's 1M and tell users that if
+      // their amount exceeded 1M
+      const assumedCircleLimit = 1_000_000;
+      const { amount } = transferDetails;
+      const limitString =
+        amount !== undefined && amount > assumedCircleLimit
```
Comment (emreboga) [inline wormhole-connect/src/utils/errors.ts:58]: Nitpick: You probably don't need to check ` amount !== undefined` if you are checking `amount > assumedCircleLimit`

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 2 above)
Comment (emreboga) [reply wormhole-connect/src/views/v2/Redeem/index.tsx]: I believe we only need to connect wallet in Redeem view when the transaction is in ready to claim state.

**Review by emreboga — DISMISSED** [review]
One minor comment, rest is LGTM.

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 2 above)
Comment (kev1n-peters) [reply wormhole-connect/src/views/v2/Redeem/index.tsx]: The tx may be in a ready to claim state while isTxDestQueued is true

File: wormhole-connect/src/utils/errors.ts (hunk 3 above)
Comment (artursapek) [reply wormhole-connect/src/utils/errors.ts:58]: yes I do https://github.com/wormholelabs-xyz/wormhole-connect/blob/9ce47c0d8010800afa765e1dc2266d85252261c0/wormhole-connect/src/telemetry/types.ts#L18

TypeScript complains otherwise

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 2 above)
Comment (artursapek) [reply wormhole-connect/src/views/v2/Redeem/index.tsx]: I dont like using gte on the receipt state because it's unclear and "happens to work". I'd like to be more explicit. how does this look @kev1n-peters ? https://github.com/wormhole-foundation/wormhole-connect/pull/2860/commits/48b72828a958620a6e8b066a447c671f190116c4

File: wormhole-connect/src/views/v2/Redeem/index.tsx [hunk 4]
```diff
@@ -164,30 +170,107 @@ const Redeem = () => {
...
+      );
+
+      setIsClaimInProgress(false);
     }
-  }, [isTxComplete]);
+  }, [
+    receipt?.state,
+    isTxComplete,
+    isTxRefunded,
+    unhandledManualClaimError,
```
Comment (kev1n-peters) [inline wormhole-connect/src/views/v2/Redeem/index.tsx:304]: We should remove one of the `unhandledManualClaimError` and add `transferSuccessEventFired` and `isAutomaticRoute`

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 2 above)
Comment (kev1n-peters) [reply wormhole-connect/src/views/v2/Redeem/index.tsx]: That looks easier to read to me

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 4 above)
Comment (artursapek) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:304]: wow oops

Comment (artursapek) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:304]: we technically dont need `transferSuccessEventFired` in this because this hook is the only thing that manipulates it. but I'll add it anyway for strictness' sake

**Review by kev1n-peters — DISMISSED** [review]

File: wormhole-connect/src/utils/errors.ts (hunk 3 above)
Comment (emreboga) [reply wormhole-connect/src/utils/errors.ts:58]: @artursapek what I meant was if the amount is undefined `amount > assumedCircleLimit` will always be falsy :)

Comment (emreboga) [reply wormhole-connect/src/utils/errors.ts:58]: Not a blocker 👍

**Review by emreboga — DISMISSED** [review]
LGTM!

File: wormhole-connect/src/utils/errors.ts (hunk 3 above)
Comment (artursapek) [reply wormhole-connect/src/utils/errors.ts:58]: I understood what you meant. like I said TypeScript is complaining if I remove this check:

image

**Review by emreboga — APPROVED** [review]
LGTM!
