### PR TITLE
fix: balance cache issue

### LINKED ISSUE #1001: [QA] Asset balance is not updated after changing wallet account
## Describe the current behavior in detail
Asset balance is not updated after changing wallet account.

Checked on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet] with macOS version 12.6.7 and Google Chrome Version 116.0.5845.179 (Official Build) (x86_64).

Steps:
1. Select Goerli network
2. Connect Metamask wallet with Account 1
3. Open Assets list
4. Change wallet account in Metamask extension
5. Connect Metamask wallet with Account 2
6. Open Assets list

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a833c83f-4994-4819-8646-6a2646001b78

## What is the expected/desired behavior
Asset balance is updated after changing wallet account.

### PR DESCRIPTION
**Pull request by anondev2323**
Please check behavior closely in case I missed something (also could probably be cleaned up).  Should resolve an error with the balances cache and changing wallets

Fixes: #1001

### CODE REVIEW

**Review by M-Picco — APPROVED** [review]

File: wormhole-connect/src/store/transferInput.ts [hunk 1]
```diff
@@ -230,16 +245,27 @@ export const transferInputSlice = createSlice({
...
+      if (!address) return;
+      // create new field for address
+      if (!state.balances[address]) {
+        state.balances = {
+          ...state.balances,
+          ...{ [address]: { [chain]: {} } },
+        };
+      }
+      state.balances[address] = {
+        [chain]: {
```
Comment (M-Picco) [inline wormhole-connect/src/store/transferInput.ts:259]: I think it's missing an object destructuring. When setting for a new chain it'll clear the other existing chains.

```suggestion
        ...state.balances[address],
        [chain]: {
```

**Review by M-Picco — CHANGES_REQUESTED** [review]

**Review by M-Picco — APPROVED** [review]
