### PR TITLE
Fixing tx tracking issues between in-progress widget and redeem view

### LINKED ISSUE #2885: [QA] "Transaction submitted" screen briefly appears when the user clicks on the completed transaction in the widget
## Describe the current behavior in detail
Checked on Netlify with following [config](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA). 

Steps:
1. Send 0.001 CELO from Celo (MetaMask) to Fantom (MetaMask) with Manual route
2. Reload the page
3. Click on "Ready to claim.." option

Actual result: "Transaction submitted" screen is displayed for a brief moment.
Expected result: "Ready to claim" screen appears immediately.

## Notes/ Attachments

Reproducibility: 3/3

https://github.com/user-attachments/assets/effe93b0-6d0f-4415-8009-a8c945db1c2a

### LINKED ISSUE #2920: [QA] "Wrapping up..." message prevents token claim via manual route
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.0.1
- Wallets: MetaMask
- Browser: Google Chrome Version 130.0.6723.92 (Official Build) (x86_64)
- https://wormhole-connect-mainnet.netlify.app/, https://preview.portalbridge.com/ac2a9a0933/

Steps to Reproduce:

1. Initiate the token transfer, e.g. 0.1 GLMR from Moonbeam to Celo
2. Select the manual route for sending tokens
3. Observe the "Wrapping up..." message that appears on the screen
4. Wait for any period of time (note that the issue is time-independent)
5. Go to the Wormholescan and copy "Source Tx Hash"
6. Resume the transaction using the Tx Hash
7. Attempt to claim the transaction 

Actual Result: The "Wrapping up..." message remains on the screen indefinitely, preventing the transaction from being claimed. The transaction can only be claimed after manually resuming it using the source Tx Hash.

Expected Result: The transaction should be claimable once the "Wrapping up..." process is complete, without the need for additional actions.

## Attachments/Notes

Examples of scenarios with the same issue:
[Arbitrum -> Optimism, CCTP Manual](https://wormholescan.io/#/tx/0xb64e40419779b01954c3b607fe24a58801688779e120c478c6472993b8379c5a)

[Solana -> Base, CCTP Manual](https://wormholescan.io/#/tx/3Mik4vj9C2AifeQc9xQnzUdAJKx68huohLymqFLEPx6VdyN49EDm9qbM3tj4VxvCjpqA3weuN7UyboUG2etWjfWd)

[Fantom -> Polygon, Token Bridge Manual](https://wormholescan.io/#/tx/0xf1f5d73f84df9e485ec049b4e7b615640938681cdcccf63d372a601acadb9c45)

[Moonbeam -> Celo, Token Bridge Manual](https://wormholescan.io/#/tx/0xcd62b8a53dc6011b6304cb781db770a1602ced9ec2f790259be262e60886e21a)

https://github.com/user-attachments/assets/edb1e610-444b-425f-a68a-ee38c2f87900

### PR DESCRIPTION
**Pull request by emreboga**
There are two main changes in this PR:
- Setting latest receipt in routeContext during tracking, which is used in Redeem view.
- useTrackTransfer now returning the latest receipt as an option property so in-progress widget can use it to set RouteContext before navigating to Redeem view.
- Display "Start new transaction" when manual tx is in progress, instead of disabled "Transfer in progress".
- Fixing more exhaustive-deps lint errors

Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/2885
Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/2920

See the loom for more details (sorry about my lower voice, still recovering since yesterday):
https://www.loom.com/share/ff58c7d63dca451680f4c7600916a66d?sid=a11ee5d8-c5ce-4ca5-9527-cc806ca9289c

### CODE REVIEW

File: wormhole-connect/src/hooks/useTrackTransfer.ts [hunk 1]
```diff
@@ -19,9 +19,10 @@ type Props = {
 type ReturnProps = {
   isCompleted: boolean;
   isReadyToClaim: boolean;
+  receipt: routes.Receipt<AttestationReceipt> | undefined;
```
Comment (emreboga) [inline wormhole-connect/src/hooks/useTrackTransfer.ts:22]: We need to provide the current receipt back to the callers to prevent out-of-date UI states.

File: wormhole-connect/src/views/v2/Redeem/index.tsx [hunk 2]
```diff
@@ -174,17 +174,24 @@ const Redeem = () => {
     tokenKey,
     receivedTokenKey,
     amount,
-    receiveAmount,
```
Comment (emreboga) [inline wormhole-connect/src/views/v2/Redeem/index.tsx:177]: This was only used as a hook dependency.

File: wormhole-connect/src/views/v2/Redeem/index.tsx [hunk 3]
```diff
@@ -610,14 +636,23 @@ const Redeem = () => {
...
+          new PublicKey(receivedToken.address.toString()),
+          new PublicKey(receivingWallet.address),
+        );
+        if (!ata.equals(new PublicKey(recipient))) {
+          setClaimError('Not connected to the receiving wallet');
+          return false;
+        }
+      } catch (e: unknown) {
+        console.log(
+          `Error while checking associated token address for the recipient: ${e}`,
```
Comment (emreboga) [inline wormhole-connect/src/views/v2/Redeem/index.tsx:651]: When an EVM wallet is connected as dest, the above call to getAssociatedTokenAddressSync throws "Non-base58 character" error. In that case we log and return false. I was thinking maybe we can also do `setClaimError('Not connected to the receiving wallet')`, but I wasn't sure if that's the only case we get this error for.

File: wormhole-connect/src/views/v2/TxHistory/Widget/Item.tsx [hunk 4]
```diff
@@ -112,6 +122,14 @@ const WidgetItem = (props: Props) => {
     }
   }, [isCompleted, txHash]);
 
+  // We have the initial receipt from local storage,
+  // but the receipt from useTrackTransfer is more up-to-date,
+  // so we need to use that one first.
+  const receipt = useMemo(
```
Comment (artursapek) [inline wormhole-connect/src/views/v2/TxHistory/Widget/Item.tsx]: probably dont need `useMemo` for this

File: wormhole-connect/src/views/v2/Redeem/index.tsx (hunk 3 above)
Comment (artursapek) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:651]: isn't it a bug that we can be in that state to begin with? if `toChain` is `Solana`, we shouldn't be able to have an EVM wallet connected in the first place.

Comment (emreboga) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:651]: This happens when user navigates from the widget to Redeem view; where toChain can be anything previously selected by the user.

Comment (artursapek) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:651]: ok. so we probably need code that looks for this state change, and auto-connects the correct wallet (or at least disconnects the incorrect one)

Comment (emreboga) [reply wormhole-connect/src/views/v2/Redeem/index.tsx:651]: opened a separate issue to track this:
https://github.com/wormhole-foundation/wormhole-connect/issues/2930

**Review by artursapek — APPROVED** [review]
