### PR TITLE
[#1212] Fix solana parsed message recipient for gateway transfers

### LINKED ISSUE #1212: [QA] [Mainnet] Incorrect wallet account on Redeem screen, tx Kujira/ Evmos -> Solana
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.001 WSOL from Kujira (Keplr) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Observe Solana wallet account

Incorrect wallet account "68Ve...1ZTv" is displayed in "To" section on Redeem screen. Wallet account "4bG8...EGdU"  is expected to be shown. Cannot connect the wallet "68Ve...1ZTv". Funds are deducted. 

Notes:
- Send from tx: [Kujira explorer](https://finder.kujira.network/kaiyo-1/tx/DF71CC18FB077548B4A7310D781D3AFD45158DCF09350E4D9455C058FF3CEBF2)
- From wallet: kujira144f7723qn9wps03j5jyflvg2xxuyxpd0ftkxxz (Keplr)
- To wallet: 4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU (Phantom)

Screenshot 2023-11-09 at 10 10 24

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ccb8a638-1080-4d65-ad64-79168d36b964

## What is the expected/desired behavior
Correct wallet account is shown.

### PR DESCRIPTION
**Pull request by M-Picco**
The recipient address for transfers from solana would not be correctly decoded to the owner account when transferring from Gateway chains. The issue would be that the token owner retrieval was performed only for payload1 type transfers, when outbound gateway transfers would be marked as payload3 when they should've been marked as payload1.

Fixes #1212

### CODE REVIEW

File: wormhole-connect/src/routes/cosmosGateway/utils/getMessage.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ export async function getUnsignedMessageFromCosmos(
     block: tx.height,
     sender: data.sender,
     gasFee: BigNumber.from(tx.gasUsed.toString()),
-    payloadID: 3, // should not be required for this case
+    payloadID: 1, // no vaa, but wormchain will eventually emit a payload1
```
Comment (sebastianscatularo) [inline wormhole-connect/src/routes/cosmosGateway/utils/getMessage.ts]:
```suggestion
    payloadID: 1, // no vaa, but wormchain will eventually emit a payload
```

**Review by sebastianscatularo — DISMISSED** [review]

**Review by kev1n-peters — APPROVED** [review]
