### PR TITLE
fix: resume native sui token bridge xfers fix

### LINKED ISSUE #3165: [QA] Infinite loading when resuming SUI token transaction
## Describe the current behavior in detail

Environment:

- OS: macOS Sequoia 15.2
- Wallets: Martian, Sui, MetaMask, Petra
- Browser: Google Chrome Version 131.0.6778.205 (Official Build) (x86_64)
- https://preview.portalbridge.com/d6931f4ac7/

Steps to Reproduce:
1. Attempt to resume a transaction involving SUI tokens
2. Observe the interface entering an endless loading state
3. Check the browser console for errors

Expected Result: The transaction should resume successfully without indefinite loading or errors.

Actual Result:
- The system becomes stuck in an endless loading state.
- Console logs the following errors:
```
Uncaught (in promise) Error: Unknown token
    at parseTokenBridgeReceipt (pb-index-FDkBUjUT.js:318:45535)
    at async parseReceipt (pb-index-FDkBUjUT.js:318:44669)
    at async Object.$t [as onClick] (pb-index-FDkBUjUT.js:552:26646)
``` 

```
Uncaught (in promise) Error: when deserializing item 'mintRecipient': chunk is shorter than expected: 133 < 145
    at updateOffset (pb-index-FDkBUjUT.js:289:10096)
    at deserializeItem (pb-index-FDkBUjUT.js:289:11935)
    at internalDeserialize (pb-index-FDkBUjUT.js:289:10318)
    at deserialize$2 (pb-index-FDkBUjUT.js:289:9863)
    at pb-index-FDkBUjUT.js:289:160518
    at deserializePayload (pb-index-FDkBUjUT.js:289:160759)
    at deserialize$1 (pb-index-FDkBUjUT.js:289:160128)
    at getVaa (pb-index-FDkBUjUT.js:291:31645)
``` 

## Attachments/Notes
#3132 - Error: when deserializing item 'mintRecipient'
#2741 - Related cases

Wormholescan links:
[Celo -> Aptos](https://wormholescan.io/#/tx/0x9d5f0f5a761c45a325116b57dbc0e9757d37b770cb40215471635a25c7bb37ce)
[Aptos -> Sui](https://wormholescan.io/#/tx/0x1d004143d36e8841635ad97908bfb706cc6d37210341ff568cace4bb8eb2b98a)
[Aptos -> Fantom](https://wormholescan.io/#/tx/0xe1c34c4f15fddf1356f6415b06d20fdc8904c315d23ac49a6810d8b3ef8d358a)

Screenshot 2025-01-09 at 10 01 13

### PR DESCRIPTION
**Pull request by kev1n-peters**
resolves: #3165

### CODE REVIEW

**Comment by kev1n-peters** [comment]
reverts https://github.com/wormhole-foundation/wormhole-connect/pull/3786/files#diff-98dd048ecf1ee9dd2ce27bd14ee8ee17633ce8d40fb2f84cdbeff15cd0782a3b

File: src/utils/sdkv2.ts [hunk 1]
```diff
@@ -584,10 +583,10 @@ const getTokenBridgeToken = async (
           address: token.address,
         });
 
-  const wrappedNative = getWrappedNativeToken(config.network, chain);
+  const wrappedNative = await tb.getWrappedNative();
 
   const tokenId =
-    wrappedNative && wrappedNative === tokenAddress.toString()
+    wrappedNative && wrappedNative.toString() === tokenAddress.toString()
```
Comment (evan-gray) [inline src/utils/sdkv2.ts:589]: any concern about casing here?

**Review by evan-gray — APPROVED** [review]
