### PR TITLE
[Redesign] Fixing which tokens to display whether a wallet is connected

### LINKED ISSUE #2674: [QA] Token list is incomplete when wallet is not connected
## Describe the current behavior in detail
Checked on https://portalbridge.com/:
* Portal Bridge: v0.2.15-191783896a
* Wormhole Connect: v^1.0.0-beta.1-development

Steps:
1. Select Arbitrum network in "From" section (Wallet was not connected)
2. Check if WAVAX or WFTM token is displayed in the list

Actual result: Tokens are not displayed in the list until wallet is connected. 
Expected result: Tokens are displayed in the list when wallet is not connected. 

## Notes/ Attachments

image

image

### PR DESCRIPTION
**Pull request by emreboga**
This PR displays all tokens supported when no wallet is connected; and the ones with a balance when a wallet is connected. Please see the loom below for details.

Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/2674

https://www.loom.com/share/8c78bd459de442b58193e6c2ff93dc03?sid=5cd50d11-a606-4914-99f6-aa92712e3221

### CODE REVIEW

**Review by artursapek — DISMISSED** [review]

**Comment by Wesleyleung** [comment]
Categories of tokens that should be included in defaults when wallet is not connected:
- Gas token for the chain (ETH on Ethereum, Avax on Avalanche, Pol on Polygon, Sui on Sui, etc)
- Canonical wrapped version of gas token for its chain (eg. WETH on Ethereum, WFTM on Fantom)
- Native stablecoins (USDC and USDT)
- Canonical versions of stablecoins if native does not yet exist (eg. wUSDC on Sui, USDC.e on Fantom)
- Any tokens integrators have configured

Frankenstein tokens and regular Wormhole-wrapped tokens that are not otherwise part of the above (ie. treated as canonical) should not be included.

When a wallet *is* connected, then show whatever the user has a balance of.

File: wormhole-connect/src/views/v2/Bridge/AssetPicker/TokenList.tsx [hunk 1]
```diff
@@ -78,51 +76,20 @@ const TokenList = (props: Props) => {
     const tokenSet: Set<string> = new Set();
     const tokens: Array<TokenConfig> = [];
 
-    const addToken = (tokenConfig: TokenConfig) => {
```
Comment (emreboga) [inline wormhole-connect/src/views/v2/Bridge/AssetPicker/TokenList.tsx:81]: This function will have different conditions for most cases below and that's why I don't think we need a separate function anymore, not much re-usability.

File: wormhole-connect/src/views/v2/Bridge/AssetPicker/TokenList.tsx [hunk 2]
```diff
@@ -131,42 +98,63 @@ const TokenList = (props: Props) => {
                 selectedChainConfig.key,
               ),
           );
-          if (destToken) {
-            addToken(destToken);
+          if (destTokenConfig && !tokenSet.has(destTokenConfig.key)) {
```
Comment (kev1n-peters) [inline wormhole-connect/src/views/v2/Bridge/AssetPicker/TokenList.tsx]: I don't think we want to add the dest token if it's frankenstein

**Review by kev1n-peters — APPROVED** [review]
