### PR TITLE
UI refresh fixes

### LINKED ISSUE #3623: [QA] Gas amount displayed as "+0" despite being correctly applied on-chain
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.5
- Wallets: Phantom, MetaMask
- Browser: Google Chrome Version 136.0.7103.114 (Official Build) (x86_64)
- [deploy-preview-3604 config
](https://deploy-preview-3604--wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtAoRFS6AA8ADtGQEc0SLDwAbOmF14ARgegBVNgCVoAMwHMAagGZps6GAC%2BZMJR%2BlDxUsIKYANqUEAB0cQAiAKIAYgCCVgAyACoA%2BrYA8lZZiQDKCooAsngAnniQtoih8mBVtfWNYRUAwlmc%2Fq11DU0lwmzJWf7RYHExerBDYQwAFKBKELCIqLoMdFNKaQByWfkVOVYl8V2Re2ura%2FcAxkyEkJhYibBMmtBUOOQ393wkDwkmQbwADCpoAAhMRdaAATjwCIAjG4xAiACzg8GJRIAdgArI43Cj4QAOMxiNyYzEANgATPFwSi8CiHij%2Fvd7hstq9sJDUuCzOS6QjUQ9GSjKW46RyxCiEfFMXgGYjEmZwQ9ErLwXSYZjyVzuUoZHUGA9oAQAG6aa4m%2B53B1rPBiMTOHYClSEwkOfHkhngtyE%2FFpFH41IoxJdMyGxIIwlKwmJOlufFmZLJBN0sR05LG52m6oaN5IZA4FiWAuFoKFsAAXXKJtrDqdDqeLzeyTqGz%2BTYdQJBdq9dPJYmhDIc4MJqVVYnx%2BKSDgR5JRDjEDLM0DcDLpdLR2IeCIZJ%2BS0OrJt5ughKgZyXxbjc4IT0PJ4KFmLMbkp4PiKK1XTkuSmKEgyKros%2BIqyngF7cmakAWlatpgmAUR1hAbZ1q67qCJ6WCQpSmL4lOar4tAgbhpiDz4nSeDLv%2BroPOCrrkngn5Bpik5UbBzqwMW0CligFaIFW%2FbOi2zqNgCigSWsUkmhk4iIDk8AMLAiRZAAEvarbSUoHZEG8HxfAIvw8Wsg6gjeZhYqxCLfgy%2BK5qxAbJHShJoqkCr%2BgidKYvEbHksR5HQvECLmaamzXl6xFuAiXSEquySJoS0KEm4DyEg8ZiKmYzJfg4Y6pHK9nJgyXR4OCEWKPBiE2sOaHoZhhbYR6N6RqkXRdCi0D6mIeATkl0BUqiOoeYSz5uMkKJJElDJZVVYmFnxJbYGWwmiXpayySa8kOjttxbRABn8lg0IWtVECWcO%2BEqGKSWElKYpktCDg6vEYjxKBmJiAS%2F40WY%2BIIsk77go5RpLTyUWnZCu6ZdALLfRuKYMm%2BqSGskDKZeCDhufE0BkaB8b7mSl1gLVlr1ShjV1s1zqtbh1nbveCOjviDKJOCYhuV08ShskwbQvieBsdCOW0nSlziqKZNFqtWDrZW0Cy74kNyWrEAHRAe33MIOkmnTawnW8JQiXUMEa4o10oVgRywLOiDxAAUkwWyadAeAuFYmmQNUTDwGYnAHKkBx0sIvDQmommoJp0JZJK87WhkADSZNXqd5KEi40LJAAigAWl0CJZPnqAOHgaiwNCwgAFbWlY8D4gAmmY%2Bc19UoHFTgNewJwADiNdqbnqQ4LnafIOalPIfrhaGyaDNCG8dsO87rvQO7nve77%2FuB8Hofh5H0ex%2FHOb4knqeWzy%2FGCeWSsq1r6tHWAACOVCIGENsHM%2FuYABrP6k5IMhmAYF0KgfdyQVAyMIYQVBOCikJAcFwdIa62BRBUMwP9oDJxUMqTSKdnbVQfhhJ%2BxtsDGW%2BGZS%2BYBrY3iYuzaEKJUiJAcI%2BfUH1oCJg%2FL5cUzDMTQHJN2JMWJ0YQyfunG80IcbdjfDiIC%2BoQzJFFG6UCfkbKJU3AyLyQUzCblROPSeSEGpP2IehRQC88KQniGYH0mJjzzkVL%2BFEZg8CJHJJ1MwnM4oojJJiHUBJOJsy1CrdY181pCTvlQzWVCdbciIWAOeihSFYFSMgMwBAZCUKfjQr06VHxiHfA8YqKoQLvjdHmaA95JaSzRESe8u4ujQkNJiNO0MJFSLwDI8EciOGhiUWIFRn4EwBh0Vo9MujORUIpoY6mxj4mzIgOYm8f4OmpGhGKBGYM9z8KFqiNkqUuhEQ8piFE6VUgTRAngOkwTyahIVuEkSytImqyfjE%2B4cSEnHWeIZbA%2BRK7aAIAwPsWTzZWS9KyTE008BAxxgyKaDgbILgZL5OUayBY5i6LmRKQY3DQDRC0vkbTcYdJxF00UPTFE5n6buQZ6iRliG0eM%2FRCEp5GNMR8l0bo2pegRHlSk6ZQL4i6OjXqD5yQPFCgNbmHkugnnpHSIkdJwQPjENclaAkwm3weffaJlt3kkK%2BadaEeAGCPOBcCUFt1ckQVSIUvybEJpeVzMkCpNF4jVLTISOpdIGlNPxdFW6kiiWdO6QovpAy1HDM0fSsZNkJliInsy6ZM9nTsqUIsr0yy3FrIRBs3c%2BpyQ7NZCc6EByiQomOac85hJLmqtuYrLVTy4na11WrV5zylA%2BAAJTlCkpQKgJr7BiEEAQXg%2FIMnyBAJQdOIDECQAcCO3YShVLqS0sAh4i61hbGqKWNSGlNJrtggwaoOAzAiR3SuzSsFgSwHql0A1bxzoPFgunNgYgN2PHvdgR95l023ThsSRGYFkaMjRhjLGE1caSwJhwjmvlvFdFggdAgDxZ1vCYLAWAagdgAHpsPGpNbABgMQUNEEkA8VAiBiOIBwNhkjCFsPaCHAwbD0pyQ0mw2pOo%2FVkBiGw8uvdMQ1CQF4LBOjfdoDkcQK%2B0sE81AaDEAAWjUnAJgomRIoDeAAYjcKkVIU18xLSHQ8RjBhPTSn7LJYQDAzbAnfYoLdbwrM2YtjcI9J6z3YGEFevAN7bR3s7NgU2BhzbPuhtJuZJoklBZC2rX9mds550LsXUu5dK7Vzrg3Zurd26dzpN3XuA8h4jzHktJDKHTrocwzhvDQg4BEbo2RijVGaN0eY4xyQzHgxdPxBx%2FQkBuO8aQDgZASscgGD4MpBwVADAGByCh8byAcjIF4GYHIgYcRqBUDkdmcmCA5HhTRWiDxM54EE8JgA%2FOGLpo5yQJmaUtMTEmKPhbuZqza9wjMmc9HSCz%2FZhAqYoTgOzEAHOeYB6ZIF9w3OnqMJ57zvnoD%2Be%2Be8T4gPQt8nC4bJJ5CIc%2Fs5YzL0gbpEkpDb0yl4ahkaNGTo2NiGlrIdQ9gSrWH0C4fw3VqjpGnuUZQy1xARA2v4A69hrrQVetcbwDxvj1GRsPLGxN%2Fb03ZvzZQEtlba2SWbe2wyXb%2B3AZ7jwMd6tZ3eCXfxNdoCd21NEHE5Jl79b3trE%2B%2FgUzmBzNTEs5LtJGSgcRc3dAbdnmvfpNkJDtY0OPNYC80ta9t7P3JNSSHzJUMMdvr9x%2BgLCfveh7xzhRehP2nBrJaG8n1KI1U%2BjTTvRpX6flbQxhlnbPauEc58J7nzXaP8%2Fo%2B1wQIuJpi84%2F1yXg2ZejfG7wSbSu5vqcW8t1b63wRa522oPbB2DdG9O0J03V3RSW8JPdm4j27dp9extU1H2JNfbd%2BSX7UxhCID%2BTgAFvvmqg6jw%2Fm9T%2FAWHuPTDxz8O49M9flP9n90ddBMdpIklgD%2Flv9Yt8d88A1C8Sdi8ydlEy9Kc6UGVaca8bgGcKsG9qt2cW8Gt29edO8BcGMhde9RcetB8Btpdhsx8FcpsZtp8Fs1d59Ncttl9V99cjsTsTczcLdbt99rdIBbdnsT8Hdz8ndL8XczMb8Pc%2FtnETVgcwA39hAVCZClAI9Yco8AC%2FN48jUTUwDIAIDIsjDjVtCOU88LEVAidiVZEUCKU0DVEMCo0sDq8bgytGcsBmdCDm96su9GsedqNyDu8qDOt%2B9aC%2Bt6ChtZdLB5cJ9FdWCVdZ91cF8l8dcV89dDtDcBCt8hDd8RCD9Hgu8JCpMpD7lHclBndDAFDb8okQAfAABuIAA%3D%3D%3D)

Steps to Reproduce:

1. Prepare to send 0.001 BNB from BSC to Moonbeam via Automatic Bridge route
2. Observe the gas estimation, which is displayed as "+0 GLMR"
3. Proceed with the transaction
4. On-chain explorer (moonscan) confirms that the correct gas amount was sent and consumed

Expected Results:

- The UI should correctly display the estimated gas amount (e.g., "+0.004967 GLMR").
- Displayed gas fee should match what is actually sent on-chain.

Actual Results:

- Gas amount is shown as "+0 GLMR" in the UI.
- The correct gas fee is sent with the transaction, confirmed on-chain.

## Attachments/Notes

[Wormholescan](https://wormholescan.io/#/tx/0xbe7948e570e425126d3152de0471c4ea76e0fe2ac3900170d0980c6ae441ea71)

Image

Image

https://github.com/user-attachments/assets/ffa931de-11b9-4aca-88bc-7b436dbc0cff

### LINKED ISSUE #3624: [QA] UI inconsistencies from Figma in new design
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.5
- Wallets: MetaMask
- Browser: Google Chrome Version 136.0.7103.114 (Official Build) (x86_64)
- [deploy-preview-3604 config
](https://deploy-preview-3604--wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtAoRFS6AA8ADtGQEc0SLDwAbOmF14ARgegBVNgCVoAMwHMAagGZps6GAC%2BZMJR%2BlDxUsIKYANqUEAB0cQAiAKIAYgCCVgAyACoA%2BrYA8lZZiQDKCooAsngAnniQtoih8mBVtfWNYRUAwlmc%2Fq11DU0lwmzJWf7RYHExerBDYQwAFKBKELCIqLoMdFNKaQByWfkVOVYl8V2Re2ura%2FcAxkyEkJhYibBMmtBUOOQ393wkDwkmQbwADCpoAAhMRdaAATjwCIAjG4xAiACzg8GJRIAdgArI43Cj4QAOMxiNyYzEANgATPFwSi8CiHij%2Fvd7hstq9sJDUuCzOS6QjUQ9GSjKW46RyxCiEfFMXgGYjEmZwQ9ErLwXSYZjyVzuUoZHUGA9oAQAG6aa4m%2B53B1rPBiMTOHYClSEwkOfHkhngtyE%2FFpFH41IoxJdMyGxIIwlKwmJOlufFmZLJBN0sR05LG52m6oaN5IZA4FiWAuFoKFsAAXXKJtrDqdDqeLzeyTqGz%2BTYdQJBdq9dPJYmhDIc4MJqVVYnx%2BKSDgR5JRDjEDLM0DcDLpdLR2IeCIZJ%2BS0OrJt5ughKgZyXxbjc4IT0PJ4KFmLMbkp4PiKK1XTkuSmKEgyKros%2BIqyngF7cmakAWlatpgmAUR1hAbZ1q67qCJ6WCQpSmL4lOar4tAgbhpiDz4nSeDLv%2BroPOCrrkngn5Bpik5UbBzqwMW0CligFaIFW%2FbOi2zqNgCigSWsUkmhk4iIDk8AMLAiRZAAEvarbSUoHZEG8HxfAIvw8Wsg6gjeZhYqxCLfgy%2BK5qxAbJHShJoqkCr%2BgidKYvEbHksR5HQvECLmaamzXl6xFuAiXSEquySJoS0KEm4DyEg8ZiKmYzJfg4Y6pHK9nJgyXR4OCEWKPBiE2sOaHoZhhbYR6N6RqkXRdCi0D6mIeATkl0BUqiOoeYSz5uMkKJJElDJZVVYmFnxJbYGWwmiXpayySa8kOjttxbRABn8lg0IWtVECWcO%2BEqGKSWElKYpktCDg6vEYjxKBmJiAS%2F40WY%2BIIsk77go5RpLTyUWnZCu6ZdALLfRuKYMm%2BqSGskDKZeCDhufE0BkaB8b7mSl1gLVlr1ShjV1s1zqtbh1nbveCOjviDKJOCYhuV08ShskwbQvieBsdCOW0nSlziqKZNFqtWDrZW0Cy74kNyWrEAHRAe33MIOkmnTawnW8JQiXUMEa4o10oVgRywLOiDxAAUkwWyadAeAuFYmmQNUTDwGYnAHKkBx0sIvDQmommoJp0JZJK87WhkADSZNXqd5KEi40LJAAigAWl0CJZPnqAOHgaiwNCwgAFbWlY8D4gAmmY%2Bc19UoHFTgNewJwADiNdqbnqQ4LnafIOalPIfrhaGyaDNCG8dsO87rvQO7nve77%2FuB8Hofh5H0ex%2FHOb4knqeWzy%2FGCeWSsq1r6tHWAACOVCIGENsHM%2FuYABrP6k5IMhmAYF0KgfdyQVAyMIYQVBOCikJAcFwdIa62BRBUMwP9oDJxUMqTSKdnbVQfhhJ%2BxtsDGW%2BGZS%2BYBrY3iYuzaEKJUiJAcI%2BfUH1oCJg%2FL5cUzDMTQHJN2JMWJ0YQyfunG80IcbdjfDiIC%2BoQzJFFG6UCfkbKJU3AyLyQUzCblROPSeSEGpP2IehRQC88KQniGYH0mJjzzkVL%2BFEZg8CJHJJ1MwnM4oojJJiHUBJOJsy1CrdY181pCTvlQzWVCdbciIWAOeihSFYFSMgMwBAZCUKfjQr06VHxiHfA8YqKoQLvjdHmaA95JaSzRESe8u4ujQkNJiNO0MJFSLwDI8EciOGhiUWIFRn4EwBh0Vo9MujORUIpoY6mxj4mzIgOYm8f4OmpGhGKBGYM9z8KFqiNkqUuhEQ8piFE6VUgTRAngOkwTyahIVuEkSytImqyfjE%2B4cSEnHWeIZbA%2BRK7aAIAwPsWTzZWS9KyTE008BAxxgyKaDgbILgZL5OUayBY5i6LmRKQY3DQDRC0vkbTcYdJxF00UPTFE5n6buQZ6iRliG0eM%2FRCEp5GNMR8l0bo2pegRHlSk6ZQL4i6OjXqD5yQPFCgNbmHkugnnpHSIkdJwQPjENclaAkwm3weffaJlt3kkK%2BadaEeAGCPOBcCUFt1ckQVSIUvybEJpeVzMkCpNF4jVLTISOpdIGlNPxdFW6kiiWdO6QovpAy1HDM0fSsZNkJliInsy6ZM9nTsqUIsr0yy3FrIRBs3c%2BpyQ7NZCc6EByiQomOac85hJLmqtuYrLVTy4na11WrV5zylA%2BAAJTlCkpQKgJr7BiEEAQXg%2FIMnyBAJQdOIDECQAcCO3YShVLqS0sAh4i61hbGqKWNSGlNJrtggwaoOAzAiR3SuzSsFgSwHql0A1bxzoPFgunNgYgN2PHvdgR95l023ThsSRGYFkaMjRhjLGE1caSwJhwjmvlvFdFggdAgDxZ1vCYLAWAagdgAHpsPGpNbABgMQUNEEkA8VAiBiOIBwNhkjCFsPaCHAwbD0pyQ0mw2pOo%2FVkBiGw8uvdMQ1CQF4LBOjfdoDkcQK%2B0sE81AaDEAAWjUnAJgomRIoDeAAYjcKkVIU18xLSHQ8RjBhPTSn7LJYQDAzbAnfYoLdbwrM2YtjcI9J6z3YGEFevAN7bR3s7NgU2BhzbPuhtJuZJoklBZC2rX9mds550LsXUu5dK7Vzrg3Zurd26dzpN3XuA8h4jzHktJDKHTrocwzhvDQg4BEbo2RijVGaN0eY4xyQzHgxdPxBx%2FQkBuO8aQDgZASscgGD4MpBwVADAGByCh8byAcjIF4GYHIgYcRqBUDkdmcmCA5HhTRWiDxM54EE8JgA%2FOGLpo5yQJmaUtMTEmKPhbuZqza9wjMmc9HSCz%2FZhAqYoTgOzEAHOeYB6ZIF9w3OnqMJ57zvnoD%2Be%2Be8T4gPQt8nC4bJJ5CIc%2Fs5YzL0gbpEkpDb0yl4ahkaNGTo2NiGlrIdQ9gSrWH0C4fw3VqjpGnuUZQy1xARA2v4A69hrrQVetcbwDxvj1GRsPLGxN%2Fb03ZvzZQEtlba2SWbe2wyXb%2B3AZ7jwMd6tZ3eCXfxNdoCd21NEHE5Jl79b3trE%2B%2FgUzmBzNTEs5LtJGSgcRc3dAbdnmvfpNkJDtY0OPNYC80ta9t7P3JNSSHzJUMMdvr9x%2BgLCfveh7xzhRehP2nBrJaG8n1KI1U%2BjTTvRpX6flbQxhlnbPauEc58J7nzXaP8%2Fo%2B1wQIuJpi84%2F1yXg2ZejfG7wSbSu5vqcW8t1b63wRa522oPbB2DdG9O0J03V3RSW8JPdm4j27dp9extU1H2JNfbd%2BSX7UxhCID%2BTgAFvvmqg6jw%2Fm9T%2FAWHuPTDxz8O49M9flP9n90ddBMdpIklgD%2Flv9Yt8d88A1C8Sdi8ydlEy9Kc6UGVaca8bgGcKsG9qt2cW8Gt29edO8BcGMhde9RcetB8Btpdhsx8FcpsZtp8Fs1d59Ncttl9V99cjsTsTczcLdbt99rdIBbdnsT8Hdz8ndL8XczMb8Pc%2FtnETVgcwA39hAVCZClAI9Yco8AC%2FN48jUTUwDIAIDIsjDjVtCOU88LEVAidiVZEUCKU0DVEMCo0sDq8bgytGcsBmdCDm96su9GsedqNyDu8qDOt%2B9aC%2Bt6ChtZdLB5cJ9FdWCVdZ91cF8l8dcV89dDtDcBCt8hDd8RCD9Hgu8JCpMpD7lHclBndDAFDb8okQAfAABuIAA%3D%3D%3D)

Issues:

1. Balance displays 0 even when no token is selected:

Actual: The interface displays 0 token balance before any token is selected.
Expected: According to the Figma design, if no token is selected, the balance should be hidden (not displayed as 0).

2. Swap arrow style differs from Figma:

Actual: The swap arrow button in the live interface has a thicker border and smaller overall size compared to the design.
Expected: The arrow should match Figma in terms of size and border thickness. Currently, it looks heavier and more compressed.

3. Alignment issues with balance and Select button before any token is selected:

Actual: The 0 balance and Select button are vertically misaligned compared to the Figma. In the current implementation:
- The balance and button appear higher.
- The spacing between the wallet address and the From label, as well as between balance/button, is reduced.

Expected: All elements should follow the vertical padding and spacing defined in the Figma for visual balance and clarity.

4. Connect Destination Wallet button is active even when destination chain is not selected:

Actual: The "Connect Destination Wallet" button appears active (clickable) even if no destination network is selected.
Expected: The button should be disabled until the user selects a destination chain, as per the Figma logic and UX best practices.

5. Place for network icon is visible before network is chosen. 

Actual result: The network icon is visible even before a network has been chosen or detected.
Expected result: The network icon should only become visible after a network has been chosen or detected.

Image

### PR DESCRIPTION
**Pull request by emreboga**
Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/3623
Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/3624

### CODE REVIEW

**Review by DBosley — DISMISSED** [review]

File: src/views/v3/Bridge/Routes/index.tsx [hunk 1]
```diff
@@ -178,12 +208,8 @@ function Routes({
   }, [selectedRoute, bestRoute]);
 
   const selectButtonDisabled = useMemo(() => {
-    return (
-      !!selectedRoute &&
-      selectedRoute === highlightedRoute &&
-      toNativeToken === gasTokenAmount / 100
-    );
-  }, [selectedRoute, highlightedRoute, toNativeToken, gasTokenAmount]);
+    return !!selectedRoute && selectedRoute === highlightedRoute;
```
Comment (priyajeet) [inline src/views/v3/Bridge/Routes/index.tsx]: Probably remove the memo

Comment (emreboga) [reply src/views/v3/Bridge/Routes/index.tsx]: https://github.com/wormhole-foundation/wormhole-connect/pull/3645/commits/e4eec0a74a84a84314e40e31730ea5c9c1c620c4

File: src/views/v3/Bridge/Routes/index.tsx [hunk 2]
```diff
@@ -62,46 +64,74 @@ function Routes({
...
+      dispatch(setToNativeToken(originalToNativeToken));
+    }
+  }, [
+    highlightedRoute,
+    originalSelectedRoute,
+    originalToNativeToken,
+    dispatch,
+  ]);
 
   const handleCloseDrawer = useCallback(() => {
```
Comment (priyajeet) [inline src/views/v3/Bridge/Routes/index.tsx:80]: BTW I think you can safely combine `handleCloseDrawer` and `handleCloseModal` and just have 1 function do both actions. `setShowModal(false)` and `setShowDrawer(false)` should be fine to have in the same function as one will be a noop. But if you really want to keep them isolated, the other parts can be unified since its the same code.

File: src/views/v3/Bridge/Routes/index.tsx [hunk 3]
```diff
@@ -62,46 +64,74 @@ function Routes({
...
     }
-    if (gasTokenAmount !== toNativeToken) {
-      dispatch(setToNativeToken(gasTokenAmount));
-    }
+
+    // Update the original values as well since user confirmed their selection
+    setOriginalToNativeToken(toNativeToken);
+    setOriginalSelectedRoute(highlightedRoute);
+
     mobile ? setShowDrawer(false) : setShowModal(false);
```
Comment (priyajeet) [inline src/views/v3/Bridge/Routes/index.tsx:133]: Similar comment as above, you can choose to not have this conditional check, just set both to false.

**Review by priyajeet — APPROVED** [review]
