### PR TITLE
[Redesign] Fixing the issue when gas topup is added

### LINKED ISSUE #2426: [QA] Blank screen appears when changing slider position - networks were swapped
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (Connect v2) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.120 (Official Build) (arm64).

Steps:
1. Prepare to send 3 USDC from Arbitrum (MetaMask) to Avalanche (MetaMask)
2. Click on Swap button
3. Select Automatic route 
4. Click on "Review transaction" button
5. Change slider position 

Actual result: Blank screen appears. 
Expected result: Slider position is changed.

## Notes/ Attachments
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2363

https://github.com/user-attachments/assets/fbc5b829-1f45-4dcc-88d3-40e4a99b6bf3

### PR DESCRIPTION
**Pull request by emreboga**
`routeOrderOfPreference` is no longer needed with sdkv2, but calling `establishRoute` was wrongly setting the route to undefined.

Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/2426

### CODE REVIEW

File: wormhole-connect/src/views/v2/Bridge/index.tsx [hunk 1]
```diff
@@ -346,7 +346,7 @@ const Bridge = () => {
       !destToken ||
       !sendingWallet.address ||
       !receivingWallet.address ||
-      routeStates?.length === 0 ||
+      !selectedRoute ||
```
Comment (emreboga) [inline wormhole-connect/src/views/v2/Bridge/index.tsx:349]: We should now show "Review transaction" button if no route is selected.

**Review by artursapek — APPROVED** [review]
