### PR TITLE
Tx history change wallet fix

### LINKED ISSUE #2622: [QA] Wallets are not loading after returning from "Transaction history" page
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQHUAEoZPnL1yEYDCKgAqOzFqwKQejYAkjIqALogAL5AA%3D%3D%3D) and https://preview.portalbridge.com/b1f3c5115d/ with macOS Sonoma 14.5 and Google Chrome Version 128.0.6613.120 (Official Build) (arm64).

Steps:
1. Select Ethereum as source chain (MetaMask wallet was auto-connected)
2. Click on "Transaction history" icon
3. Click on swap button to return to "Bridge assets" screen
4. Click on wallet address
5. Select "Change wallet" option

Actual result: Wallets are not displayed. 
Expected result: Wallets are displayed. 

## Notes/ Attachments

image

https://github.com/user-attachments/assets/df1fda28-9b94-470a-b5cb-92a368c4bd46

### PR DESCRIPTION
**Pull request by kev1n-peters**
Fixes https://github.com/wormhole-foundation/wormhole-connect/issues/2622

### CODE REVIEW

File: wormhole-connect/src/AppRouter.tsx [hunk 1]
```diff
@@ -80,9 +79,9 @@ function AppRouter(props: Props) {
       config.whLegacy.registerProviders(); // reset providers that may have been set during transfer
     }
     // reset transfer state on leave
-    if (route === bridgeRoute && prevRoute !== bridgeRoute) {
+    const isEnteringBridge = route === bridgeRoute && prevRoute !== bridgeRoute;
+    if (isEnteringBridge && prevRoute !== 'history') {
       dispatch(clearTransfer());
-      dispatch(clearPorticoBridge());
```
Comment (kev1n-peters) [inline wormhole-connect/src/AppRouter.tsx:85]: We should remove this from the store, but it has cascading changes, so didn't want to do it here

**Review by yuli-ferna — DISMISSED** [review]

File: wormhole-connect/src/AppRouter.tsx (hunk 1 above)
Comment (artursapek) [reply wormhole-connect/src/AppRouter.tsx:85]: can you add `TODO SDKV2` comment somewhere to remind us?

**Review by artursapek — DISMISSED** [review]

File: wormhole-connect/src/AppRouter.tsx (hunk 1 above)
Comment (kev1n-peters) [reply wormhole-connect/src/AppRouter.tsx:85]: done

**Review by yuli-ferna — APPROVED** [review]
